<h1>Tasks</h1>
<?php if (count($this->tasks)): ?>
  <table class="table table-hover table-responsive">
    <thead>
      <tr>
        <th>TaskID</th>
        <th>Start</th>
        <th>Ende</th>
        <th>Keywords</th>
        <th>Fertig?</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($this->tasks as $task): ?>
        <tr class="<?= is_null($task->rating) ? 'warning' : ($task->rating < 0.5 ? 'danger' : 'success'); ?>">
          <td>
            <? if($task->completed_at): ?>
              <a href="<?=$this->url(array('action' => 'detail','task' => $task->id),'default',true)?>"><?= $task->id ?></a>
            <? else: ?>
              <?= $task->id ?>
            <? endif; ?>
          </td>
          <td><?= date("d.m.Y",strtotime($task->start)) ?></td>
          <td><?= date("d.m.Y",strtotime($task->end)) ?></td>
          <td><?= implode(', ',$task->keywords) ?></td>
          <td><?= $task->completed_at ? 'Y' : 'N' ?></td>
          <td>
            <a href="<?=$this->url(array('action' => 'delete', 'id' => $task->id),'default',true)?>"><span class="glyphicon glyphicon-trash"></span></a>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>

<?php else: ?>
  <p>No tasks.</p>
<?php endif; ?>