<?=$this->doctype();?>
<html lang="en">
  <head>
    <?= $this->headMeta() ?>
    <meta charset="utf-8">
    <?= $this->headTitle() ?>
    <?= $this->headLink() ?>
    <?=$this->headStyle() ?>

  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">TwitSentAnalysis</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class=""><a href="/">Home</a></li>
            <li class=""><a href="<?=$this->url(array('action' => 'new'),'default',true);?>">Neue Abfrage</a></li>

            <!--li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li-->
          </ul>
          <!--ul class="nav navbar-nav navbar-right">
            <li><a href="#">#1</a></li>
            <li><a href="#">#2</a></li>
            <li class="active"><a href="#">#3</a></li>
          </ul-->
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <?php echo $this->layout()->content; ?>
      </div>

    </div> <!-- /container -->

    <? $this->jQuery()->setVersion('1')->enable(); ?>
    <?= $this->jQuery()->setUiVersion('1')->UiEnable(); ?>
    <?=$this->headScript(); ?>
  </body>
</html>
